# Generated by Django 4.1.7 on 2023-03-07 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=250)),
                ('phno', models.IntegerField()),
                ('mailid', models.CharField(max_length=250)),
                ('addres', models.CharField(max_length=250)),
                ('account_type', models.CharField(max_length=250)),
                ('materials', models.CharField(max_length=250)),
                ('branch', models.ForeignKey(db_column='branch', on_delete=django.db.models.deletion.CASCADE, to='credentials.branches')),
                ('district', models.ForeignKey(db_column='district', on_delete=django.db.models.deletion.CASCADE, to='credentials.district')),
            ],
        ),
        migrations.AddField(
            model_name='branches',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credentials.district'),
        ),
    ]
